# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.26.1"

# Site settings
title: whoami730's blog
title_separator: "|"
name: "Sahil Jain"
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal homepage where I usually blog about fun stuff
  in tech, rant or express my views.
logo: /assets/images/logo.jpg
url: "https://whoami730.github.io"
repository: "whoami730/whoami730.github.io"
atom_feed:
  hide: true

# Site author
author:
  name: "Sahil Jain"
  avatar: "/assets/images/me.png"
  bio: "Who am I?"
  email: jsahil730@gmail.com
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/whoami730"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sahil-jain-a637b0190/"

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"
    label: "comments" # Optional - must be existing label.


# Reading files
include: [_pages]
markdown_ext: "md"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-gist

defaults:
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: single
      permalink: /blog/:title/
      author_profile: true
      show_date: true
      read_time: true
      comments: true
      share: true
  -
    scope:
      type: pages
      path: _pages
    values:
      is_post: false
      layout: single
      permalink: /:basename/
      author_profile: true

timezeon: Asia/Kolkata

enable_copy_code_button: true
